---
version: "2.4"

volumes:
  elasticsearch_data:
  percona_data:
  composer_deps:
  dip_uploads_data:
    external:
      name: "dip-upload-data"
  archivematica_pipeline_data:
    external:
      name: "am-pipeline-data"

services:

  atom:
    build: ..
    env_file: etc/environment
    volumes:
      - composer_deps:/atom/src/vendor/composer
      - ..:/atom/src:rw
      - "dip_uploads_data:/var/archivematica/dip-uploads:rw"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    depends_on:
      percona:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      memcached:
        condition: service_started
      gearmand:
        condition: service_started

  atom_worker:
    build: ..
    command: worker
    env_file: etc/environment
    depends_on:
      percona:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      gearmand:
        condition: service_started  
    restart: on-failure:5
    volumes:
      - composer_deps:/atom/src/vendor/composer
      - ..:/atom/src:rw
      - "dip_uploads_data:/var/archivematica/dip-uploads:rw"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"

  nginx:
    image: nginx:latest
    volumes:
      - ..:/atom/src:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "63001:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    env_file: etc/environment
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:63002:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  percona:
    image: percona:8.0
    env_file: etc/environment
    volumes:
      - percona_data:/var/lib/mysql:rw
      - ./etc/mysql/mysqld.cnf:/etc/my.cnf.d/mysqld.cnf:ro
    ports:
      - "127.0.0.1:63003:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -pmy-secret-pw ping --silent"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  memcached:
    image: memcached
    command: -p 11211 -m 128 -u memcache
    ports:
      - "127.0.0.1:63004:11211"

  gearmand:
    image: artefactual/gearmand
    ports:
      - "127.0.0.1:63005:4730"
