---
version: "2.4"

volumes:
  elasticsearch_data:
  percona_data:
  composer_deps:
  dip_uploads_data:
    external:
      name: "dip-upload-data"

services:

  atom:
    build: ..
    container_name: atom
    image: ${DOCKER_REGISTRY:?registry}/atom:latest
    env_file: etc/environment
    volumes:
      - "dip_uploads_data:/var/archivematica/dip-uploads:rw"
    depends_on:
      percona:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      memcached:
        condition: service_started
      gearmand:
        condition: service_started
    restart: unless-stopped

  atom_worker:
    build: ..
    container_name: atom_worker
    image: ${DOCKER_REGISTRY:?registry}/atom-worker:latest
    command: worker
    env_file: etc/environment
    depends_on:
      percona:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      gearmand:
        condition: service_started  
    restart: unless-stopped
    volumes:
      - "dip_uploads_data:/var/archivematica/dip-uploads:rw"

  nginx:
    image: nginx:latest
    container_name: atom_nginx
    volumes:
      - ..:/atom/src:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - atom      
    ports:
      - "63001:80"
    restart: unless-stopped

  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: atom_elasticsearch
    env_file: etc/environment
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:63002:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  percona:
    image: percona:8.0
    container_name: atom_percona
    env_file: etc/environment
    volumes:
      - percona_data:/var/lib/mysql:rw
      - ./etc/mysql/mysqld.cnf:/etc/my.cnf.d/mysqld.cnf:ro
    ports:
      - "127.0.0.1:63003:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -pmy-secret-pw ping --silent"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  memcached:
    image: memcached
    container_name: atom_memcached
    command: -p 11211 -m 128 -u memcache
    ports:
      - "127.0.0.1:63004:11211"

  gearmand:
    image: artefactual/gearmand
    container_name: atom_gearmand
    ports:
      - "127.0.0.1:63005:4730"

